--
-- База данных: agency
--

-- --------------------------------------------------------

--
-- Структура таблицы store
--

CREATE TABLE store (
  store_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop varchar(50) NOT NULL,
  street varchar(50) NOT NULL,
  house varchar(20) NOT NULL,
  phone varchar(250) NOT NULL,
  town varchar(30) NOT NULL,
  town_eng varchar(30) DEFAULT NULL,
  locality_id integer,
  date_store date NOT NULL
);

--
-- Дамп данных таблицы store
--